### ISSUE TITLE
Connect Functionality

### ISSUE THREAD

**Issue by ssutcher** [wodory/flowmate#5]
I can't seem to get the connect functionality to work. Any insight here?

**Comment by wodory** [comment]
I guess I must update the code for sketch 3.4 :-( I'll do ASAP!

**Comment by ssutcher** [comment]
Thanks! Sketch updates have been killing me lately.

**Comment by wodory** [comment]
Dear ssutcher!

I fix the bug LOL. Just modify one API name .... :-(
Just remove and re-install it.

(The company never support what the API name are changed... suck...)
