### ISSUE TITLE
What is the logic to determine which input is first

### ISSUE THREAD

**Issue by Conaws** [wodory/flowmate#6]
Let's say I have three elements, and I want to draw a connection between 3 and 1

![frame 01](https://cloud.githubusercontent.com/assets/2712495/14933614/41f55a70-0e62-11e6-9a8c-066d857f383c.png)

How can I control what the first and second arguments are to the draw connection command

![frame 01](https://cloud.githubusercontent.com/assets/2712495/14933618/6a66fc98-0e62-11e6-8386-55a5f617a170.png)

**Comment by wodory** [comment]
I update plugin and fix the problem, too. Hope happy new to you.
