### ISSUE TITLE
Just started..

### ISSUE THREAD

**Issue by uxwithleti** [wodory/flowmate#7]
I have just downloaded this and tried to use it but nothing is happening.. is there a problem?

**Comment by Visuacom** [comment]
Same problem, nothing happens :(

**Comment by sosheepster** [comment]
Possibly because the plugin is outdated. You guys might want to give AEFlowchart a try, since it currently works with the latest version of Sketch.

**Comment by wodory** [comment]
Sorry, guys. As sosheepster said, I didn't update the new scripts yet. I'll try to fix it and let you know it.

**Comment by wodory** [comment]
I update the plugin. I'm so sorry too late. (The document of Sketch API is... really... not good...)
